Repository prgrms-web-devcourse/Team-03-LinkBook-BE, pull requests merged in 2022-08, with the labels that each got.

#25 🐛폴더 태그 연관관계매핑 수정 및 해결
  src/main/java/com/prgrms/team03linkbookbe/folder/dto/FolderDetailResponse.java
  src/main/java/com/prgrms/team03linkbookbe/folder/dto/FolderResponse.java
  src/main/java/com/prgrms/team03linkbookbe/folder/entity/Folder.java
  src/main/java/com/prgrms/team03linkbookbe/tag/entity/Tag.java
Labels: 🐛 Bug

#22 [FEAT] 북마크 CRUD
  src/main/java/com/prgrms/team03linkbookbe/bookmark/controller/BookmarkController.java
  src/main/java/com/prgrms/team03linkbookbe/bookmark/dto/BookmarkIdResponse.java
  src/main/java/com/prgrms/team03linkbookbe/bookmark/dto/BookmarkRequest.java
  src/main/java/com/prgrms/team03linkbookbe/bookmark/entity/Bookmark.java
  src/main/java/com/prgrms/team03linkbookbe/bookmark/service/BookmarkService.java
  src/main/java/com/prgrms/team03linkbookbe/folder/controller/FolderController.java
  src/main/java/com/prgrms/team03linkbookbe/folder/dto/FolderDetailResponse.java
  src/main/java/com/prgrms/team03linkbookbe/folder/service/FolderService.java
  src/main/java/com/prgrms/team03linkbookbe/like/repository/LikeRepository.java
Labels: 👽 API, ✨ Feature

#30 [FEAT] 로그인, 회원가입, 인증&인가 구현
  build.gradle
  src/main/java/com/prgrms/team03linkbookbe/common/controller/GlobalExceptionHandler.java
  src/main/java/com/prgrms/team03linkbookbe/common/exception/ExceptionCode.java
  src/main/java/com/prgrms/team03linkbookbe/common/exception/GlobalExceptionHandler.java
  src/main/java/com/prgrms/team03linkbookbe/common/exception/NoDataException.java
  src/main/java/com/prgrms/team03linkbookbe/config/JwtConfigure.java
  src/main/java/com/prgrms/team03linkbookbe/config/WebSecurityConfigure.java
  src/main/java/com/prgrms/team03linkbookbe/folder/entity/Folder.java
  src/main/java/com/prgrms/team03linkbookbe/jwt/ExceptionHandlerFilter.java
  src/main/java/com/prgrms/team03linkbookbe/jwt/Jwt.java
  src/main/java/com/prgrms/team03linkbookbe/jwt/JwtAuthentication.java
  src/main/java/com/prgrms/team03linkbookbe/jwt/JwtAuthenticationFilter.java
  src/main/java/com/prgrms/team03linkbookbe/jwt/JwtAuthenticationProvider.java
  src/main/java/com/prgrms/team03linkbookbe/jwt/JwtAuthenticationToken.java
  src/main/java/com/prgrms/team03linkbookbe/jwt/exception/AccessDeniedException.java
  src/main/java/com/prgrms/team03linkbookbe/jwt/exception/AccessTokenExpiredException.java
  src/main/java/com/prgrms/team03linkbookbe/jwt/exception/IllegalTokenException.java
  src/main/java/com/prgrms/team03linkbookbe/jwt/exception/RefreshTokenExpiredException.java
  src/main/java/com/prgrms/team03linkbookbe/refreshtoken/controller/RefreshTokenController.java
  src/main/java/com/prgrms/team03linkbookbe/refreshtoken/dto/AccessTokenResponseDto.java
  src/main/java/com/prgrms/team03linkbookbe/refreshtoken/entity/RefreshToken.java
  src/main/java/com/prgrms/team03linkbookbe/refreshtoken/repository/RefreshTokenRepository.java
  src/main/java/com/prgrms/team03linkbookbe/refreshtoken/service/RefreshTokenService.java
  src/main/java/com/prgrms/team03linkbookbe/sample/controller/Sample.java
  src/main/java/com/prgrms/team03linkbookbe/user/controller/UserController.java
  src/main/java/com/prgrms/team03linkbookbe/user/controller/UserControllerAdvice.java
  src/main/java/com/prgrms/team03linkbookbe/user/dto/LoginRequestDto.java
  src/main/java/com/prgrms/team03linkbookbe/user/dto/LoginResponseDto.java
  src/main/java/com/prgrms/team03linkbookbe/user/dto/RegisterRequestDto.java
  src/main/java/com/prgrms/team03linkbookbe/user/dto/RegisterResponseDto.java
  src/main/java/com/prgrms/team03linkbookbe/user/dto/UpdateRequestDto.java
  src/main/java/com/prgrms/team03linkbookbe/user/dto/UserResponseDto.java
  src/main/java/com/prgrms/team03linkbookbe/user/entity/User.java
  src/main/java/com/prgrms/team03linkbookbe/user/exception/DuplicatedEmailException.java
  src/main/java/com/prgrms/team03linkbookbe/user/exception/LoginFailureException.java
  src/main/java/com/prgrms/team03linkbookbe/user/repository/UserRepository.java
  src/main/java/com/prgrms/team03linkbookbe/user/service/UserService.java
  src/main/resources/application.yaml
Labels: ✨ Feature

#36 [BUG] EC2 build 실패 오류 해결 (Hotfix)
  .github/workflows/github-action.yml
  src/main/java/com/prgrms/team03linkbookbe/bookmark/controller/BookmarkController.java
  src/main/java/com/prgrms/team03linkbookbe/folder/entity/Folder.java
  src/test/java/com/prgrms/team03linkbookbe/integration/comment/CommentIntegrationTest.java
Labels: 👽 API, 🐛 Bug

#38 [SETTING] CI/CD 플로우 수정 : PR 발행 → build 만 실행, main branch push → Deploy 실행
  .github/workflows/build.yml
  .github/workflows/deploy.yml
Labels: 💣 CI/CD, 🌏 Deploy, 👋 self-approve

#33 [FEAT] User, RefreshToken 컨트롤러 단위 테스트 추가
  src/main/java/com/prgrms/team03linkbookbe/bookmark/controller/BookmarkController.java
  src/main/java/com/prgrms/team03linkbookbe/folder/entity/Folder.java
  src/main/java/com/prgrms/team03linkbookbe/jwt/JwtAuthenticationToken.java
  src/main/java/com/prgrms/team03linkbookbe/refreshtoken/controller/RefreshTokenController.java
  src/main/java/com/prgrms/team03linkbookbe/refreshtoken/service/RefreshTokenService.java
  src/main/java/com/prgrms/team03linkbookbe/user/controller/UserController.java
  src/main/java/com/prgrms/team03linkbookbe/user/dto/LoginRequestDto.java
  src/main/java/com/prgrms/team03linkbookbe/user/dto/RegisterRequestDto.java
  src/main/java/com/prgrms/team03linkbookbe/user/dto/UserResponse.java
  src/main/java/com/prgrms/team03linkbookbe/user/service/UserService.java
  src/test/java/com/prgrms/team03linkbookbe/annotation/WithJwtAuth.java
  src/test/java/com/prgrms/team03linkbookbe/annotation/WithJwtAuthSecurityContextFactory.java
  src/test/java/com/prgrms/team03linkbookbe/unit/refreshtoken/controller/RefreshTokenControllerUnitTest.java
  src/test/java/com/prgrms/team03linkbookbe/unit/user/controller/UserControllerUnitTest.java
Labels: ✅ Test

#23 [SETTING] Github Action : NGINX 도커 빌드 및 실행 로직 추가
  .github/workflows/deploy.yml
Labels: 💣 CI/CD, 🌏 Deploy

#42 [FEAT] RefreshToken 통합 테스트 작성
  src/main/java/com/prgrms/team03linkbookbe/user/controller/UserController.java
  src/main/java/com/prgrms/team03linkbookbe/user/dto/UserLoginResponseDto.java
  src/main/java/com/prgrms/team03linkbookbe/user/dto/UserUpdateRequestDto.java
  src/main/java/com/prgrms/team03linkbookbe/user/entity/User.java
  src/main/java/com/prgrms/team03linkbookbe/user/service/UserService.java
  src/test/java/com/prgrms/team03linkbookbe/integration/refreshtoken/RefreshTokenIntegrationTest.java
  src/test/java/com/prgrms/team03linkbookbe/unit/user/controller/UserControllerUnitTest.java
  src/test/java/com/prgrms/team03linkbookbe/unit/user/service/UserServiceTest.java
Labels: ✅ Test

#45 [bug] 댓글, 좋아요 테스트 오류 수정
  src/main/java/com/prgrms/team03linkbookbe/comment/service/CommentService.java
  src/main/java/com/prgrms/team03linkbookbe/like/service/LikeService.java
  src/test/java/com/prgrms/team03linkbookbe/unit/comment/service/CommentServiceTest.java
  src/test/java/com/prgrms/team03linkbookbe/unit/like/service/LikeServiceTest.java
Labels: 👽 API, 🐛 Bug

#46 :bug:댓글, 좋아요 테스트 오류 수정
  src/test/java/com/prgrms/team03linkbookbe/integration/comment/CommentIntegrationTest.java
  src/test/java/com/prgrms/team03linkbookbe/integration/like/LikeIntegrationTest.java
Labels: 🐛 Bug

#47 :recycle: User Response 통합
  src/main/java/com/prgrms/team03linkbookbe/comment/dto/CommentResponse.java
  src/main/java/com/prgrms/team03linkbookbe/folder/dto/FolderDetailResponse.java
  src/main/java/com/prgrms/team03linkbookbe/folder/dto/FolderListResponse.java
  src/main/java/com/prgrms/team03linkbookbe/folder/dto/FolderResponse.java
  src/main/java/com/prgrms/team03linkbookbe/like/dto/LikeResponse.java
  src/main/java/com/prgrms/team03linkbookbe/refreshtoken/dto/AccessTokenResponseDto.java
  src/main/java/com/prgrms/team03linkbookbe/user/controller/UserController.java
  src/main/java/com/prgrms/team03linkbookbe/user/dto/LoginResponseDto.java
  src/main/java/com/prgrms/team03linkbookbe/user/dto/MeResponseDto.java
  src/main/java/com/prgrms/team03linkbookbe/user/dto/RegisterResponseDto.java
  src/main/java/com/prgrms/team03linkbookbe/user/dto/UserDetailResponseDto.java
  src/main/java/com/prgrms/team03linkbookbe/user/dto/UserLoginResponseDto.java
  src/main/java/com/prgrms/team03linkbookbe/user/dto/UserSimpleResponseDto.java
  src/main/java/com/prgrms/team03linkbookbe/user/service/UserService.java
  src/test/java/com/prgrms/team03linkbookbe/integration/refreshtoken/RefreshTokenIntegrationTest.java
  src/test/java/com/prgrms/team03linkbookbe/integration/user/UserIntegrationTest.java
  src/test/java/com/prgrms/team03linkbookbe/unit/user/controller/UserControllerUnitTest.java
  src/test/java/com/prgrms/team03linkbookbe/unit/user/service/UserServiceTest.java
Labels: ♻️ Refactor, 👋 self-approve

#50 [FEAT] 인증, 인가 필요 없는 API 설정 추가
  src/main/java/com/prgrms/team03linkbookbe/config/WebSecurityConfigure.java
Labels: ✨ Feature, 👋 self-approve

#52 [REFACTOR] Like Get 모두 허용으로 변경
  src/main/java/com/prgrms/team03linkbookbe/config/WebSecurityConfigure.java
Labels: ♻️ Refactor, 👋 self-approve

#56 [FEAT] CORS 모두 허용 추가
  src/main/java/com/prgrms/team03linkbookbe/config/WebSecurityConfigure.java
Labels: ✨ Feature, 👋 self-approve

#60 [REFACTOR] 댓글 수정 부분 수정
  src/main/java/com/prgrms/team03linkbookbe/comment/dto/UpdateCommentRequest.java
Labels: 👽 API, ♻️ Refactor

#57 feat i 28
  build.gradle
  src/main/java/com/prgrms/team03linkbookbe/bookmark/dto/BookmarkRequest.java
  src/main/java/com/prgrms/team03linkbookbe/bookmark/repository/BookmarkRepository.java
  src/main/java/com/prgrms/team03linkbookbe/bookmark/service/BookmarkService.java
  src/main/java/com/prgrms/team03linkbookbe/folder/dto/FolderResponse.java
  src/test/java/com/prgrms/team03linkbookbe/integration/BookmarkTest.java
  src/test/java/com/prgrms/team03linkbookbe/unit/bookmark/controller/BookmarkControllerTest.java
  src/test/java/com/prgrms/team03linkbookbe/unit/bookmark/entity/BookmarkTest.java
  src/test/java/com/prgrms/team03linkbookbe/unit/bookmark/repository/BookmarkRepositoryTest.java
  src/test/java/com/prgrms/team03linkbookbe/unit/bookmark/service/BookmarkServiceTest.java
Labels: 👽 API, ✨ Feature, 👋 self-approve

#63 [BUG] 폴더부분 버그 수정
  src/main/java/com/prgrms/team03linkbookbe/config/WebSecurityConfigure.java
  src/main/java/com/prgrms/team03linkbookbe/folder/dto/FolderDetailResponse.java
Labels: 🐛 Bug, 👋 self-approve

#61 [FEAT] User 통합 테스트 작성
  src/main/java/com/prgrms/team03linkbookbe/bookmark/service/BookmarkService.java
  src/main/java/com/prgrms/team03linkbookbe/common/exception/ExceptionCode.java
  src/main/java/com/prgrms/team03linkbookbe/user/dto/RegisterRequestDto.java
  src/main/java/com/prgrms/team03linkbookbe/user/dto/UserDetailResponseDto.java
  src/main/java/com/prgrms/team03linkbookbe/user/entity/User.java
  src/test/java/com/prgrms/team03linkbookbe/integration/refreshtoken/RefreshTokenIntegrationTest.java
  src/test/java/com/prgrms/team03linkbookbe/integration/user/UserIntegrationTest.java
Labels: ♻️ Refactor, ✅ Test, 👋 self-approve

#65 [bug] 댓글 부분 오류 수정
  src/main/java/com/prgrms/team03linkbookbe/comment/controller/CommentController.java
  src/main/java/com/prgrms/team03linkbookbe/comment/dto/CreateCommentRequest.java
  src/main/java/com/prgrms/team03linkbookbe/comment/service/CommentService.java
  src/test/java/com/prgrms/team03linkbookbe/unit/comment/controller/CommentControllerTest.java
  src/test/java/com/prgrms/team03linkbookbe/unit/comment/service/CommentServiceTest.java
Labels: 👽 API, 🐛 Bug

#72 :bug: cors preflight 허용 추가
  src/main/java/com/prgrms/team03linkbookbe/config/WebSecurityConfigure.java
Labels: 🐛 Bug, 👋 self-approve

#73 [feat] 이메일 인증 기능 구현
  .gitignore
  src/main/java/com/prgrms/team03linkbookbe/common/exception/ExceptionCode.java
  src/main/java/com/prgrms/team03linkbookbe/config/EmailConfig.java
  src/main/java/com/prgrms/team03linkbookbe/config/WebSecurityConfigure.java
  src/main/java/com/prgrms/team03linkbookbe/email/controller/EmailController.java
  src/main/java/com/prgrms/team03linkbookbe/email/controller/EmailControllerAdvice.java
  src/main/java/com/prgrms/team03linkbookbe/email/dto/EmailCertificationRequestDto.java
  src/main/java/com/prgrms/team03linkbookbe/email/dto/EmailRequestDto.java
  src/main/java/com/prgrms/team03linkbookbe/email/exception/EmailCertificationFailureException.java
  src/main/java/com/prgrms/team03linkbookbe/email/exception/EmailSendFailureException.java
  src/main/java/com/prgrms/team03linkbookbe/email/service/EmailService.java
  src/main/java/com/prgrms/team03linkbookbe/user/service/UserService.java
  src/main/resources/application.yaml
  src/test/java/com/prgrms/team03linkbookbe/integration/email/EmailIntegrationTest.java
  src/test/java/com/prgrms/team03linkbookbe/unit/email/controller/EmailControllerUnitTest.java
  src/test/java/com/prgrms/team03linkbookbe/unit/email/service/EmailServiceTest.java
  src/test/java/com/prgrms/team03linkbookbe/unit/user/service/UserServiceTest.java
  src/test/resources/application.yaml
Labels: ✨ Feature

#71 [REFACTOR] 좋아요 + 댓글 Serivce 유효성 검사 추가
  src/main/java/com/prgrms/team03linkbookbe/comment/service/CommentService.java
  src/main/java/com/prgrms/team03linkbookbe/like/service/LikeService.java
  src/test/java/com/prgrms/team03linkbookbe/unit/like/service/LikeServiceTest.java
Labels: 👽 API, ♻️ Refactor

#78 [FEAT] 회원가입 시에 인증 이메일 검증 추가
  src/main/java/com/prgrms/team03linkbookbe/common/exception/ExceptionCode.java
  src/main/java/com/prgrms/team03linkbookbe/email/exception/EmailIsNotCertificatedException.java
  src/main/java/com/prgrms/team03linkbookbe/email/service/EmailService.java
  src/main/java/com/prgrms/team03linkbookbe/user/controller/UserController.java
  src/main/java/com/prgrms/team03linkbookbe/user/controller/UserControllerAdvice.java
  src/main/java/com/prgrms/team03linkbookbe/user/service/UserService.java
  src/test/java/com/prgrms/team03linkbookbe/integration/email/EmailIntegrationTest.java
  src/test/java/com/prgrms/team03linkbookbe/integration/user/UserIntegrationTest.java
  src/test/java/com/prgrms/team03linkbookbe/unit/email/controller/EmailControllerUnitTest.java
  src/test/java/com/prgrms/team03linkbookbe/unit/email/service/EmailServiceTest.java
  src/test/java/com/prgrms/team03linkbookbe/unit/user/controller/UserControllerUnitTest.java
  src/test/java/com/prgrms/team03linkbookbe/unit/user/service/UserServiceTest.java
Labels: ✨ Feature

#74 ♻️[REFECTOR] 폴더피드백반영
  src/main/java/com/prgrms/team03linkbookbe/bookmark/controller/BookmarkController.java
  src/main/java/com/prgrms/team03linkbookbe/bookmark/dto/BookmarkRequest.java
  src/main/java/com/prgrms/team03linkbookbe/bookmark/repository/BookmarkRepository.java
  src/main/java/com/prgrms/team03linkbookbe/bookmark/service/BookmarkService.java
  src/main/java/com/prgrms/team03linkbookbe/config/WebSecurityConfigure.java
  src/main/java/com/prgrms/team03linkbookbe/folder/dto/CreateFolderRequest.java
  src/main/java/com/prgrms/team03linkbookbe/folder/dto/FolderDetailResponse.java
  src/main/java/com/prgrms/team03linkbookbe/folder/dto/FolderListResponse.java
  src/main/java/com/prgrms/team03linkbookbe/folder/dto/FolderResponse.java
  src/main/java/com/prgrms/team03linkbookbe/folder/repository/FolderRepository.java
  src/main/java/com/prgrms/team03linkbookbe/folder/service/FolderService.java
  src/main/java/com/prgrms/team03linkbookbe/folderTag/repository/FolderTagRepository.java
  src/main/java/com/prgrms/team03linkbookbe/folderTag/service/FolderTagService.java
  src/main/java/com/prgrms/team03linkbookbe/rootTag/controller/RootTagController.java
  src/main/java/com/prgrms/team03linkbookbe/rootTag/dto/RootTagListResponse.java
  src/main/java/com/prgrms/team03linkbookbe/rootTag/dto/RootTagResponse.java
  src/main/java/com/prgrms/team03linkbookbe/rootTag/entity/RootTag.java
  src/main/java/com/prgrms/team03linkbookbe/rootTag/entity/RootTagCategory.java
  src/main/java/com/prgrms/team03linkbookbe/rootTag/repository/RootTagRepository.java
  src/main/java/com/prgrms/team03linkbookbe/tag/controller/TagController.java
  src/main/java/com/prgrms/team03linkbookbe/tag/dto/TagResponse.java
  src/main/java/com/prgrms/team03linkbookbe/tag/entity/Tag.java
  src/main/java/com/prgrms/team03linkbookbe/tag/entity/TagCategory.java
  src/main/java/com/prgrms/team03linkbookbe/tag/service/TagService.java
  src/test/java/com/prgrms/team03linkbookbe/unit/bookmark/controller/BookmarkControllerTest.java
  src/test/java/com/prgrms/team03linkbookbe/unit/bookmark/service/BookmarkServiceTest.java
Labels: ♻️ Refactor, 👋 self-approve

#80 [feat] 태그 추가 기능개발
  src/main/java/com/prgrms/team03linkbookbe/rootTag/entity/RootTagCategory.java
Labels: 👽 API, ✨ Feature, 👋 self-approve

#81 :sparkles:[FEAT] 폴더 제목으로 검색 기능 개발
  src/main/java/com/prgrms/team03linkbookbe/folder/controller/FolderController.java
  src/main/java/com/prgrms/team03linkbookbe/folder/repository/FolderRepository.java
  src/main/java/com/prgrms/team03linkbookbe/folder/service/FolderService.java
Labels: 👽 API, ✨ Feature, 👋 self-approve

#82 [FEAT] 루트 태그, 태그로 검색기능 추가
  .gitignore
  src/main/java/com/prgrms/team03linkbookbe/folder/controller/FolderController.java
  src/main/java/com/prgrms/team03linkbookbe/folder/dto/FolderListResponse.java
  src/main/java/com/prgrms/team03linkbookbe/folder/dto/RootTagRequest.java
  src/main/java/com/prgrms/team03linkbookbe/folder/dto/TagRequest.java
  src/main/java/com/prgrms/team03linkbookbe/folder/entity/Folder.java
  src/main/java/com/prgrms/team03linkbookbe/folder/repository/FolderRepository.java
  src/main/java/com/prgrms/team03linkbookbe/folder/service/FolderService.java
  src/main/java/com/prgrms/team03linkbookbe/folderTag/repository/FolderTagRepository.java
  src/main/java/com/prgrms/team03linkbookbe/tag/repository/TagRepository.java
  src/main/java/com/prgrms/team03linkbookbe/user/service/UserService.java
Labels: ✨ Feature, 👋 self-approve

#83 ♻️[REFECTOR] 좋아요한 폴더 표시 추가
  .gitignore
  src/main/java/com/prgrms/team03linkbookbe/folder/controller/FolderController.java
  src/main/java/com/prgrms/team03linkbookbe/folder/dto/FolderDetailResponse.java
  src/main/java/com/prgrms/team03linkbookbe/folder/dto/FolderListByUserResponse.java
  src/main/java/com/prgrms/team03linkbookbe/folder/dto/FolderListResponse.java
  src/main/java/com/prgrms/team03linkbookbe/folder/dto/FolderResponse.java
  src/main/java/com/prgrms/team03linkbookbe/folder/service/FolderService.java
  src/main/java/com/prgrms/team03linkbookbe/like/dto/LikeResponse.java
  src/main/java/com/prgrms/team03linkbookbe/like/service/LikeService.java
Labels: 👽 API, ♻️ Refactor, 👋 self-approve

#85 [REFACTOR] Folder 쿼리 DISTINCT 추가
  src/main/java/com/prgrms/team03linkbookbe/folder/repository/FolderRepository.java
  src/main/java/com/prgrms/team03linkbookbe/folderTag/repository/FolderTagRepository.java
Labels: ♻️ Refactor, 👋 self-approve

#91 [REFACTOR] 태그로 폴더 검색 리팩토링
  src/main/java/com/prgrms/team03linkbookbe/folder/repository/FolderRepository.java
  src/main/java/com/prgrms/team03linkbookbe/folder/service/FolderService.java
  src/main/java/com/prgrms/team03linkbookbe/folderTag/repository/FolderTagRepository.java
Labels: ♻️ Refactor, 👋 self-approve

#92 :sparkles:[FEAT] 좋아요 부분 통합테스트 개발
  src/main/java/com/prgrms/team03linkbookbe/like/controller/LikeController.java
  src/main/java/com/prgrms/team03linkbookbe/like/service/LikeService.java
  src/test/java/com/prgrms/team03linkbookbe/integration/like/LikeIntegrationTest.java
  src/test/java/com/prgrms/team03linkbookbe/unit/like/controller/LikeControllerTest.java
Labels: 👽 API, ✅ Test, 👋 self-approve

#94 :sparkles:[FEAT] 댓글 부분 통합테스트 개발
  src/main/java/com/prgrms/team03linkbookbe/comment/controller/CommentController.java
  src/test/java/com/prgrms/team03linkbookbe/integration/comment/CommentIntegrationTest.java
  src/test/java/com/prgrms/team03linkbookbe/unit/comment/controller/CommentControllerTest.java
Labels: 👽 API, ✅ Test, 👋 self-approve

#96 :sparkles:[FEAT] 폴더 세부조회 시 원본폴더 정보 보기 구현
  src/main/java/com/prgrms/team03linkbookbe/folder/dto/FolderDetailResponse.java
  src/main/java/com/prgrms/team03linkbookbe/folder/dto/OriginFolderResponse.java
  src/main/java/com/prgrms/team03linkbookbe/folder/dto/OriginUserResponse.java
  src/main/java/com/prgrms/team03linkbookbe/folder/service/FolderService.java
Labels: 👽 API, ✨ Feature, ✅ Test

#97 [FEAT] 폴더 서비스, 레파지토리 단위 테스트 작성
  src/main/java/com/prgrms/team03linkbookbe/folder/dto/CreateFolderRequest.java
  src/main/java/com/prgrms/team03linkbookbe/folder/dto/RootTagRequest.java
  src/main/java/com/prgrms/team03linkbookbe/folder/dto/TagRequest.java
  src/main/java/com/prgrms/team03linkbookbe/folder/service/FolderService.java
  src/test/java/com/prgrms/team03linkbookbe/unit/folder/repository/FolderRepositoryUnitTest.java
  src/test/java/com/prgrms/team03linkbookbe/unit/folder/service/FolderServiceUnitTest.java
Labels: ✅ Test, 👋 self-approve

#98 [feat] 폴더 통합테스트
  src/main/java/com/prgrms/team03linkbookbe/common/exception/ExceptionCode.java
  src/main/java/com/prgrms/team03linkbookbe/folder/controller/FolderController.java
  src/main/java/com/prgrms/team03linkbookbe/folder/dto/FolderDetailResponse.java
  src/main/java/com/prgrms/team03linkbookbe/folder/exception/IllegalAccessToPrivateFolderException.java
  src/main/java/com/prgrms/team03linkbookbe/folder/repository/FolderRepository.java
  src/main/java/com/prgrms/team03linkbookbe/folder/service/FolderService.java
  src/test/java/com/prgrms/team03linkbookbe/integration/folder/FolderIntegrationTest.java
  src/test/java/com/prgrms/team03linkbookbe/integration/like/LikeIntegrationTest.java
  src/test/java/com/prgrms/team03linkbookbe/unit/folder/service/FolderServiceUnitTest.java
Labels: ✨ Feature, ✅ Test, 👋 self-approve

#101 :sparkles:[FEAT] 폴더 수정 삭제 생성 통합테스트 구현
  src/test/java/com/prgrms/team03linkbookbe/integration/folder/FolderIntegrationTest.java
Labels: 👽 API, ✅ Test, 👋 self-approve

#103 [FEAT] User Interest Update 구현 & Test Code 수정
  src/main/java/com/prgrms/team03linkbookbe/interest/dto/InterestDto.java
  src/main/java/com/prgrms/team03linkbookbe/interest/entity/Field.java
  src/main/java/com/prgrms/team03linkbookbe/interest/entity/Interest.java
  src/main/java/com/prgrms/team03linkbookbe/interest/entity/SubTag.java
  src/main/java/com/prgrms/team03linkbookbe/interest/entity/TagGroup.java
  src/main/java/com/prgrms/team03linkbookbe/interest/service/InterestService.java
  src/main/java/com/prgrms/team03linkbookbe/user/dto/UserDetailResponseDto.java
  src/main/java/com/prgrms/team03linkbookbe/user/dto/UserUpdateRequestDto.java
  src/main/java/com/prgrms/team03linkbookbe/user/entity/User.java
  src/main/java/com/prgrms/team03linkbookbe/user/service/UserService.java
  src/test/java/com/prgrms/team03linkbookbe/integration/user/UserIntegrationTest.java
  src/test/java/com/prgrms/team03linkbookbe/unit/interest/repository/InterestRepositoryTest.java
  src/test/java/com/prgrms/team03linkbookbe/unit/interest/service/InterestServiceTest.java
  src/test/java/com/prgrms/team03linkbookbe/unit/user/repository/UserRepositoryTest.java
  src/test/java/com/prgrms/team03linkbookbe/unit/user/service/UserServiceTest.java
Labels: ✨ Feature

#104 [test] 북마크, 폴더 통합테스트작성
  src/main/java/com/prgrms/team03linkbookbe/rootTag/entity/RootTag.java
  src/test/java/com/prgrms/team03linkbookbe/integration/bookmark/BookmarkIntegrationTest.java
  src/test/java/com/prgrms/team03linkbookbe/integration/folder/FolderIntegrationTest.java
Labels: ✅ Test, 👋 self-approve

#106 :bug:[BUG]폴더 세부 조회시 원본 폴더 정보 보기 복구
  src/main/java/com/prgrms/team03linkbookbe/folder/service/FolderService.java
Labels: 👽 API, 🐛 Bug, 👋 self-approve

#107 [FEAT] 폴더 통합 테스트 수정
  src/test/java/com/prgrms/team03linkbookbe/integration/folder/FolderIntegrationTest.java
Labels: ✅ Test, 👋 self-approve

#109 [FEAT] 사용자 통합 테스트 수정
  src/test/java/com/prgrms/team03linkbookbe/integration/user/UserIntegrationTest.java
Labels: ✅ Test, 👋 self-approve

#110 [FEAT] 사용자 통합 테스트 수정
  src/test/java/com/prgrms/team03linkbookbe/integration/folder/FolderIntegrationTest.java
Labels: ✅ Test, 👋 self-approve

#112 [SETTING] RestDoc build.gradle 설정
  build.gradle
Labels: 🛠 Setting

#116 [SETTING] RestDoc index.html 배포
  src/docs/asciidoc/index.adoc
  src/main/resources/static/docs/index.html
Labels: 🛠 Setting

#120 [BUG] 액세스 토큰 재발급 통합 테스트 수정
  src/test/java/com/prgrms/team03linkbookbe/integration/refreshtoken/RefreshTokenIntegrationTest.java
Labels: 🐛 Bug, 👋 self-approve

#119 :recycle:좋아요 삭제 로직 변경
  src/main/java/com/prgrms/team03linkbookbe/like/controller/LikeController.java
  src/main/java/com/prgrms/team03linkbookbe/like/repository/LikeRepository.java
  src/main/java/com/prgrms/team03linkbookbe/like/service/LikeService.java
  src/test/java/com/prgrms/team03linkbookbe/integration/like/LikeIntegrationTest.java
  src/test/java/com/prgrms/team03linkbookbe/unit/like/service/LikeServiceTest.java
Labels: 👽 API, ♻️ Refactor, 👋 self-approve

#122 :recycle:댓글, 좋아요 통합테스트 수정
  src/test/java/com/prgrms/team03linkbookbe/integration/comment/CommentIntegrationTest.java
  src/test/java/com/prgrms/team03linkbookbe/integration/like/LikeIntegrationTest.java
Labels: ♻️ Refactor, ✅ Test, 👋 self-approve

#123 [FEAT] 폴더 컨트롤러 단위 테스트 작성
  src/test/java/com/prgrms/team03linkbookbe/unit/folder/controller/FolderControllerUnitTest.java
Labels: ✅ Test, 👋 self-approve

#127 [FEAT] pinned response 유저 dto 추가
  BOOT-INF/classes/static/docs/index.html
  src/main/java/com/prgrms/team03linkbookbe/folder/dto/PinnedResponse.java
  src/main/java/com/prgrms/team03linkbookbe/folder/repository/FolderRepository.java
  src/main/resources/static/docs/index.html
  src/test/java/com/prgrms/team03linkbookbe/integration/folder/FolderIntegrationTest.java
Labels: ✨ Feature, 👋 self-approve

#129 :recycle:[REFACTOR]폴더 자세히 보기 댓글 출력 및 좋아요, 댓글 에러 출력 수정
  src/main/java/com/prgrms/team03linkbookbe/comment/service/CommentService.java
  src/main/java/com/prgrms/team03linkbookbe/folder/dto/FolderDetailResponse.java
  src/main/java/com/prgrms/team03linkbookbe/like/service/LikeService.java
  src/test/java/com/prgrms/team03linkbookbe/integration/folder/FolderIntegrationTest.java
Labels: 👽 API, ♻️ Refactor, 👋 self-approve

#131 [FEAT] 루트 태그 전체 카테고리 조회 기능 추가
  src/main/java/com/prgrms/team03linkbookbe/folder/service/FolderService.java
  src/main/java/com/prgrms/team03linkbookbe/rootTag/entity/RootTagCategory.java
Labels: ✨ Feature, 👋 self-approve

#133 :bug: 폴더 생성 시 contents "" 오류 수정
  src/main/java/com/prgrms/team03linkbookbe/folder/dto/CreateFolderRequest.java
  src/main/java/com/prgrms/team03linkbookbe/folder/entity/Folder.java
Labels: 🐛 Bug, 👋 self-approve

#135 :recycle:[REFACTOR] 폴더 리스트 조회 시 isPrivate 확인 여부 수정
  src/main/java/com/prgrms/team03linkbookbe/folder/repository/FolderRepository.java
  src/main/java/com/prgrms/team03linkbookbe/folder/service/FolderService.java
  src/test/java/com/prgrms/team03linkbookbe/unit/folder/service/FolderServiceUnitTest.java
Labels: 👽 API, ♻️ Refactor, 👋 self-approve

#137 :recycle:폴더 조회 쿼리 수정
  src/main/java/com/prgrms/team03linkbookbe/folder/repository/FolderRepository.java
Labels: 👽 API, ♻️ Refactor, 👋 self-approve

#139 [REFACTOR] pinned 폴더 response 수정
  BOOT-INF/classes/static/docs/index.html
  src/main/java/com/prgrms/team03linkbookbe/folder/dto/PinnedResponse.java
  src/main/resources/static/docs/index.html
  src/test/java/com/prgrms/team03linkbookbe/integration/folder/FolderIntegrationTest.java
Labels: ♻️ Refactor, 👋 self-approve

#141 :recycle:[REFACTOR] 태그 검색 로직 수정
  src/main/java/com/prgrms/team03linkbookbe/folder/controller/FolderController.java
  src/main/java/com/prgrms/team03linkbookbe/folder/service/FolderService.java
  src/test/java/com/prgrms/team03linkbookbe/integration/folder/FolderIntegrationTest.java
  src/test/java/com/prgrms/team03linkbookbe/unit/folder/controller/FolderControllerUnitTest.java
  src/test/java/com/prgrms/team03linkbookbe/unit/folder/service/FolderServiceUnitTest.java
Labels: 👽 API, ♻️ Refactor, 👋 self-approve

#142 :recycle:[REFACTOR] 태그 검색 로직 수정 docs 업데이트
  BOOT-INF/classes/static/docs/index.html
  src/main/resources/static/docs/index.html
Labels: 📝 Docs, ♻️ Refactor, 👋 self-approve

#144 [BUG] isPinned, isPrivate 같게 나오는 오류 수정
  src/main/java/com/prgrms/team03linkbookbe/folder/dto/PinnedResponse.java
Labels: 🐛 Bug, 👋 self-approve

#147 [BUG] Access-Token exceptioncode 수정
  src/main/java/com/prgrms/team03linkbookbe/jwt/exception/AccessTokenExpiredException.java
Labels: 🐛 Bug

#149 [SETTING] Readme.md update
  README.md
Labels: 🛠 Setting

#151 [SETTING] Readme.md 이미지 수정
  README.md
Labels: 🛠 Setting

#153 [FEAT] Tag Enum 필드 추가
  src/main/java/com/prgrms/team03linkbookbe/rootTag/entity/RootTagCategory.java
  src/main/java/com/prgrms/team03linkbookbe/tag/entity/TagCategory.java
Labels: 👽 API, ✨ Feature, 👋 self-approve

#156 [BUG] 태그 관련 이슈
  src/main/java/com/prgrms/team03linkbookbe/interest/entity/SubTag.java
Labels: 👽 API, 🐛 Bug, 👋 self-approve

#159 [SETTING] Readme.md 업데이트
  README.md
Labels: 🛠 Setting

#162 [BUG] folder service unit test : 폴더생성버그수정
  src/main/java/com/prgrms/team03linkbookbe/folder/service/FolderService.java
  src/test/java/com/prgrms/team03linkbookbe/integration/folder/FolderIntegrationTest.java
  src/test/java/com/prgrms/team03linkbookbe/unit/folder/repository/FolderRepositoryUnitTest.java
  src/test/java/com/prgrms/team03linkbookbe/unit/folder/service/FolderServiceUnitTest.java
Labels: 🐛 Bug, 👋 self-approve

#163 [FEAT] 필요없는 태그 삭제
  src/main/java/com/prgrms/team03linkbookbe/rootTag/entity/RootTagCategory.java
  src/main/java/com/prgrms/team03linkbookbe/tag/entity/TagCategory.java
Labels: ♻️ Refactor, 👋 self-approve

#166 [FEAT] 폴더 북마크 Advice추가
  src/main/java/com/prgrms/team03linkbookbe/common/controller/GlobalExceptionHandler.java
  src/main/java/com/prgrms/team03linkbookbe/common/exception/ExceptionCode.java
  src/main/java/com/prgrms/team03linkbookbe/common/response/ExceptionResponse.java
  src/main/java/com/prgrms/team03linkbookbe/folder/controller/FolderControllerAdvice.java
  src/main/java/com/prgrms/team03linkbookbe/folder/exception/IllegalAccessToPrivateFolderException.java
Labels: ✨ Feature, 👋 self-approve

#168 [REFACTOR] Interest Enum 수정
  src/main/java/com/prgrms/team03linkbookbe/interest/entity/SubTag.java
  src/main/java/com/prgrms/team03linkbookbe/interest/entity/TagGroup.java
  src/test/java/com/prgrms/team03linkbookbe/integration/user/UserIntegrationTest.java
  src/test/java/com/prgrms/team03linkbookbe/unit/interest/repository/InterestRepositoryTest.java
  src/test/java/com/prgrms/team03linkbookbe/unit/interest/service/InterestServiceTest.java
  src/test/java/com/prgrms/team03linkbookbe/unit/user/repository/UserRepositoryTest.java
  src/test/java/com/prgrms/team03linkbookbe/unit/user/service/UserServiceTest.java
Labels: ♻️ Refactor

#171 :bug:[BUG] 좋아요 폴더 연관관계 버그 수정
  src/main/java/com/prgrms/team03linkbookbe/like/entity/Like.java
Labels: 👽 API, 🐛 Bug, 👋 self-approve

#172 :bug:좋아요 폴더 연관관계 버그 수정
  src/main/java/com/prgrms/team03linkbookbe/folder/entity/Folder.java
  src/main/java/com/prgrms/team03linkbookbe/like/entity/Like.java
Labels: 👽 API, 🐛 Bug, 👋 self-approve

#173 [FEAT] 유저 엔터티, dto 검증 추가
  BOOT-INF/classes/static/docs/index.html
  src/main/java/com/prgrms/team03linkbookbe/common/exception/ExceptionCode.java
  src/main/java/com/prgrms/team03linkbookbe/user/controller/UserController.java
  src/main/java/com/prgrms/team03linkbookbe/user/controller/UserControllerAdvice.java
  src/main/java/com/prgrms/team03linkbookbe/user/dto/LoginRequestDto.java
  src/main/java/com/prgrms/team03linkbookbe/user/dto/RegisterRequestDto.java
  src/main/java/com/prgrms/team03linkbookbe/user/dto/UserUpdateRequestDto.java
  src/main/java/com/prgrms/team03linkbookbe/user/entity/User.java
  src/main/java/com/prgrms/team03linkbookbe/user/exception/IllegalPasswordException.java
  src/main/java/com/prgrms/team03linkbookbe/user/service/UserService.java
  src/test/java/com/prgrms/team03linkbookbe/integration/user/UserIntegrationTest.java
  src/test/java/com/prgrms/team03linkbookbe/unit/user/controller/UserControllerUnitTest.java
  src/test/java/com/prgrms/team03linkbookbe/unit/user/service/UserServiceTest.java
Labels: ✨ Feature, 👋 self-approve
