Repository prgrms-web-devcourse/Team-03-LinkBook-BE, pull requests merged in 2022-07, with the labels that each got.

#2 [SETTING] PR 템플릿 생성
  .github/pull_request_template.md
Labels: 📝 Docs, 🛠 Setting

#4 [SETTING] Github Action & Slack 연동
  .github/workflows/github-action.yml
Labels: 💣 CI/CD, 🛠 Setting

#8 [FEAT] entity class 구현
  .gitignore
  build.gradle
  src/main/java/com/prgrms/team03linkbookbe/bookmark/entity/Bookmark.java
  src/main/java/com/prgrms/team03linkbookbe/bookmark/repository/BookMarkRepository.java
  src/main/java/com/prgrms/team03linkbookbe/comment/entity/Comment.java
  src/main/java/com/prgrms/team03linkbookbe/comment/repository/CommentRepository.java
  src/main/java/com/prgrms/team03linkbookbe/common/entity/BaseDateEntity.java
  src/main/java/com/prgrms/team03linkbookbe/config/JpaAuditConfiguration.java
  src/main/java/com/prgrms/team03linkbookbe/folder/entity/Folder.java
  src/main/java/com/prgrms/team03linkbookbe/folder/repository/FolderRepository.java
  src/main/java/com/prgrms/team03linkbookbe/hashtag/entity/Field.java
  src/main/java/com/prgrms/team03linkbookbe/hashtag/entity/Hashtag.java
  src/main/java/com/prgrms/team03linkbookbe/hashtag/repository/HashtagRepository.java
  src/main/java/com/prgrms/team03linkbookbe/interest/entity/Field.java
  src/main/java/com/prgrms/team03linkbookbe/interest/entity/Interest.java
  src/main/java/com/prgrms/team03linkbookbe/interest/repository/InterestRepository.java
  src/main/java/com/prgrms/team03linkbookbe/like/entity/Like.java
  src/main/java/com/prgrms/team03linkbookbe/like/repository/LikeRepository.java
  src/main/java/com/prgrms/team03linkbookbe/user/entity/User.java
  src/main/java/com/prgrms/team03linkbookbe/user/repository/UserRepository.java
  src/test/java/com/prgrms/team03linkbookbe/integration/sample.md
  src/test/java/com/prgrms/team03linkbookbe/unit/sample.md
Labels: 🛠 Setting

#14 [SETTING] 테스트 커버리지 측정 Flow 도입
  build.gradle
Labels: 🛠 Setting, ✅ Test

#15 [FEAT] Exception Response class 구현
  src/main/java/com/prgrms/team03linkbookbe/common/exception/ExceptionCode.java
  src/main/java/com/prgrms/team03linkbookbe/common/exception/GlobalExceptionHandler.java
  src/main/java/com/prgrms/team03linkbookbe/common/exception/NoDataException.java
  src/main/java/com/prgrms/team03linkbookbe/common/response/ExceptionResponse.java
Labels: 🛠 Setting

#18 [FEAT] 댓글 CRUD 레포지터리 & 테스트 구현
  build.gradle
  src/main/java/com/prgrms/team03linkbookbe/comment/dto/CommentResponseDto.java
  src/main/java/com/prgrms/team03linkbookbe/comment/dto/CreateCommentRequestDto.java
  src/main/java/com/prgrms/team03linkbookbe/comment/dto/CreateCommentResponseDto.java
  src/main/java/com/prgrms/team03linkbookbe/comment/dto/UpdateCommentRequestDto.java
  src/main/java/com/prgrms/team03linkbookbe/comment/dto/UpdateCommentResponseDto.java
  src/main/java/com/prgrms/team03linkbookbe/comment/entity/Comment.java
  src/main/java/com/prgrms/team03linkbookbe/comment/repository/CommentRepository.java
  src/main/java/com/prgrms/team03linkbookbe/comment/service/CommentService.java
  src/main/java/com/prgrms/team03linkbookbe/common/entity/BaseDateEntity.java
  src/main/java/com/prgrms/team03linkbookbe/folder/entity/Folder.java
  src/main/java/com/prgrms/team03linkbookbe/user/entity/User.java
  src/test/java/com/prgrms/team03linkbookbe/unit/comment/repository/CommentRepositoryTest.java
  src/test/java/com/prgrms/team03linkbookbe/unit/comment/service/CommentServiceTest.java
Labels: 👽 API, ✨ Feature, ✅ Test
